//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmf_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_log
    {
        public int co_Id { get; set; }
        public int project_Id { get; set; }
        public string co_num { get; set; }
        public Nullable<int> proc { get; set; }
        public Nullable<int> n_proc { get; set; }
        public string gc_co { get; set; }
        public string description { get; set; }
        public Nullable<int> owed { get; set; }
        public string notes { get; set; }
    
        public virtual project project { get; set; }
    }
}
