//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmf_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int project_Id { get; set; }
        public Nullable<int> project_number { get; set; }
        public string project_name { get; set; }
        public int pm_Id { get; set; }
    
        public virtual proj_man proj_man { get; set; }
    }
}
