//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pmf_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_project
    {
        public int user_proj_Id { get; set; }
        public string user_Id { get; set; }
        public int project_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual project project { get; set; }
    }
}
